In [13]:
import numpy as np
from scipy.stats import kstest
import torch
input = np.loadtxt("data.txt", dtype=float, delimiter=',')
prob_ls = (input[:, 10])
choices = (np.round_(input[:, 0:10]))
print(prob_ls)
print(choices)


data = np.random.choice(  
    a = np.arange(prob_ls.size),  
    size = 1000,  
    p = prob_ls
 )                                                                                                                                                                                                                                                        
print(data)   


[0.00027396 0.00034054 0.00026133 ... 0.00617644 0.00822258 0.01692838]
[[1. 1. 1. ... 1. 1. 1.]
 [0. 1. 1. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 1. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[ 891 1010  707  459  270  537  962  661  990  909 1012  461   37 1004
  857  221  927  539  612  824  822  323  618  647  380  690  637  709
  616  947  270 1008  727   35 1023  617 1018  813 1008  938  392  562
  937  776  511  967  981  230  707   12 1020  792 1003  833  414  645
  993  242  738  753  682  966  715  988  901  679  956  630  955  913
 1004  999   52  991 1018  521  857  455  879  234  586  378  625  678
  643  922  671  699  388  278 1009 1004  511  855  905  110  897  977
   74  991  761 1023  178  771  259  687 1002  769  983  993  711  984
  533  432  522  704 1023  881  984  240  987  869  241  874  698  810
  314  118  857  935  855  921  149  617  633  389  547  998  968  462
  182  947  643  801  976  952   85  937  959  976  286  932  

In [14]:
d1 = [choices[data], prob_ls]

In [19]:
def binlist_to_int(a):
   return int(''.join(list(map(lambda x: str(int(x)), a))), 2)

def spin_flip(d):
    choices = d[0]
    transformed_choices = [1 - x for x in choices]
    return [transformed_choices, d[1]]



def random_flip(d):
    prob_ls = np.flip(d[1])
    return [d[0], prob_ls]



#d1 is of the form [[[0., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
 #      [0., 0., 0., 0., 1., 1., 0., 1., 0., 0.],
 #      [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.]], [0.2, 0.2, 0.6]]
def KS(d1, d2, n):
    choices1 = d1[0]
    prob1 = d1[1]
    choices2 = d2[0]
    prob2 = d2[1]
    
    data1 = np.random.choice(  
    a = np.arange(prob1.size),  
    size = n,  
    p = prob1
 )
    data2 = np.random.choice(  
    a = np.arange(prob2.size),  
    size = n,  
    p = prob2
 )
    data1 = choices[data1]
    data2 = choices[data2]
    
    int_data1 = np.array([binlist_to_int(d) for d in data1])
    int_data2 = np.array([binlist_to_int(d) for d in data2])
    
    return kstest(int_data1, int_data2)

In [21]:
print("Analyzing distributions...", flush=True, end='')
distribution0 = [choices, prob_ls]
distribution1 = spin_flip(distribution0)
distribution2 = random_flip(distribution0)
print(KS(distribution0, distribution1, 1000))
print("done")
print(KS(distribution0, distribution2, 1000))

Analyzing distributions...KstestResult(statistic=0.053, pvalue=0.12051526066065596)
done
KstestResult(statistic=0.279, pvalue=1.1478066332583852e-34)
