In [ ]:
print("hello world")

In [2]:
import numpy as np 
data = np.random.choice(  
    a=[0, 1, 2],  
   size=50,  
    p=[0.5, 0.3, 0.2]  
 )                                                                                                                                                                                                                                                        
print(data)                                                                                                                                                                                                                                             

[2 0 0 1 2 0 0 2 0 1 0 1 1 0 1 2 2 2 0 1 1 0 0 2 1 1 0 1 1 0 1 2 1 0 1 2 0
 1 0 0 2 2 1 1 0 2 1 0 0 2]


In [14]:
import numpy as np
import scipy 
import torch
input = np.loadtxt("data.txt", dtype=float, delimiter=',')
prob_ls = (input[:, 10])
choices = (np.round_(input[:, 0:10]))
print(prob_ls)
print(choices)


data = np.random.choice(  
    a = np.arange(prob_ls.size),  
    size = 3,  
    p = prob_ls
 )                                                                                                                                                                                                                                                        
print(data)   


[0.00027396 0.00034054 0.00026133 ... 0.00617644 0.00822258 0.01692838]
[[1. 1. 1. ... 1. 1. 1.]
 [0. 1. 1. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 1. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[851 866 967]


In [15]:
choices[data]

array([[0., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1., 0., 1., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
def binlist_to_int(a):
   return int(''.join(list(map(str, a))), 2)




#d1 is of the form [[[0., 0., 0., 0., 0., 0., 1., 1., 1., 0.],
 #      [0., 0., 0., 0., 1., 1., 0., 1., 0., 0.],
 #      [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.]], [0.2, 0.2, 0.6]]
def KS(d1, d2, n):
    choices1 = d1[0]
    prob1 = d1[1]
    choices2 = d2[0]
    prob2 = d2[1]
    
    data1 = np.random.choice(  
    a = np.arange(prob1.size),  
    size = n,  
    p = prob1
 )
    data2 = np.random.choice(  
    a = np.arange(prob2.size),  
    size = n,  
    p = prob2
 )
    data1 = choices[data1]
    data2 = choices[data2]
    
    int_data1 = np.array([binlist_to_int(d) for d in data1])
    int_data2 = np.array([binlist_to_int(d) for d in data2])
    
    return stats.kstest(int_data1, int_data2)